name: MacOS Build

on:
  push:
    branches: [ "main", "macos-build" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release
  OS_TAG : macos
  # Just to make vscode happy. These will be set for real
  # in the config-info step
  SF_PROJECT : ""
  SF_VERSION : ""
  SF_PROJ_LOWER : ""
  SF_ARTIFACT_PATH : ""
  SF_BUILD_FILE : ""


jobs:
  build:
    runs-on: 'macos-latest'
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Get Config Info
      id: config-info
      working-directory: ${{github.workspace}}
      shell : bash
      run : |
        ./scripts/project_vars.sh > CONFIG.sh
        cat CONFIG.sh
        cat CONFIG.sh >> $GITHUB_ENV
        cat CONFIG.sh >> $GITHUB_OUTPUT

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -v

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: Pluginval MacOS
      working-directory: ${{github.workspace}}/build
      run: |
        curl -L "https://github.com/Tracktion/pluginval/releases/latest/download/pluginval_macOS.zip" -o pluginval.zip
        unzip pluginval
        pluginval.app/Contents/MacOS/pluginval --strictness-level 5 --validate-in-process --output-dir "." \
          "Source/${SF_PROJECT}_artefacts/Release/VST3/${{env.SF_ARTIFACT_PATH}}/${{env.SF_BUILD_FILE}}" || exit 1

    - name: Create DMG
      working-directory: ${{github.workspace}}/build
      run : |
        mkdir ${SF_PROJECT}
        ln -s /Library/Audio/Plug-Ins/VST3 ${SF_PROJECT}/Library
        cp -R "Source/${SF_PROJECT}_artefacts/Release/VST3/${SF_ARTIFACT_PATH}/${SF_BUILD_FILE}" ${SF_PROJECT}
        hdiutil create -fs JHFS+ ${SF_PROJECT}-V${SF_VERSION}-${{env.OS_TAG}}-universal.dmg \
          -srcfolder $SF_PROJECT \
          -ov -format UDZO

    - name: Upload plugin
      uses: actions/upload-artifact@v3
      with:
        name: ${{env.SF_PROJECT}}-V${{env.SF_VERSION}}-${{env.OS_TAG}}-universal.dmg
        path: ${{github.workspace}}/build/${{env.SF_PROJECT}}-V${{env.SF_VERSION}}-${{env.OS_TAG}}-universal.dmg

