name: Release Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release


jobs:
  build:
    strategy :
      matrix :
        os : [ windows-latest, ubuntu-latest]
        include :
          - os : windows-latest
            artifact_path : "${{vars.SF_PLUGIN_NAME}}.vst3/Contents/x86_64-win"
            file : ${{vars.SF_PLUGIN_NAME}}.vst3
            artifact_name : win64
          # macos is seg faulting when running juce_vst3_helper
          #- os : macos-latest
          #  artifact_path : "${{vars.SF_PLUGIN_NAME}}.vst3/Contents/MacOS"
          #  file : ${{vars.SF_PLUGIN_NAME}}
          #  artifact_name : macos
          - os : ubuntu-latest
            artifact_path : "."
            file : ${{vars.SF_PLUGIN_NAME}}.vst3
            artifact_name : linux
    
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Configure ubuntu
      if : matrix.os == 'ubuntu-latest'
      run : |
       sudo apt install xorg-dev libasound2-dev libgl1-mesa-dev  \
            libcurl4-openssl-dev libwebkit2gtk-4.0-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -v

    - name: Get Config Info
      id: config-info
      working-directory: ${{github.workspace}}/build
      shell : bash
      run : |
        ../scripts/project_vars > CONFIG.sh
        cat CONFIG.sh
        cat CONFIG.sh >> $GITHUB_ENV
        cat CONFIG.sh >> $GITHUB_OUTPUT

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: Pluginval MacOS
      working-directory: ${{github.workspace}}/build
      if: matrix.os == 'macos-latest'
      run: |
        curl -L "https://github.com/Tracktion/pluginval/releases/latest/download/pluginval_macOS.zip" -o pluginval.zip
        unzip pluginval
        pluginval.app/Contents/MacOS/pluginval --strictness-level 5 --validate-in-process --output-dir "." "Source/${SF_PROJECT}_artefacts/Release/VST3/${{matrix.artifact_path}}" || exit 1

    - name: Pluginval Linux
      working-directory: ${{github.workspace}}/build
      if: matrix.os == 'linux-latest'
      run: |
        curl -L "https://github.com/Tracktion/pluginval/releases/latest/download/pluginval_Linux.zip" -o pluginval.zip
        unzip pluginval
        ./pluginval --validate-in-process --strictness-level 5 --output-dir "." "Source/${SF_PROJECT}_artefacts/Release/VST3/${{matrix.artifact_path}}" || exit 1

    - name: Pluginval Linux
      working-directory: ${{github.workspace}}/build
      if: matrix.os == 'windows-latest'
      run: |
        "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; Invoke-WebRequest https://github.com/Tracktion/pluginval/releases/latest/download/pluginval_Windows.zip -OutFile pluginval.zip"
        "Expand-Archive pluginval.zip -DestinationPath ."
        pluginval.exe --validate-in-process --strictness-level 5 --output-dir "." "Source/${SF_PROJECT}_artefacts/Release/VST3/${{matrix.artifact_path}}"
        if %ERRORLEVEL% neq 0 exit /b 1
  

    - name: Compress plugin not-win
      if : matrix.os != 'windows-latest'
      working-directory: ${{github.workspace}}/build
      run : |
        cd Source/${SF_PROJECT}_artefacts/Release/VST3/${{matrix.artifact_path}}
        ZIPNAME="${SF_PROJECT}-V${SF_VERSION}-${{matrix.artifact_name}}-vst3.zip"
        zip -9 -r ${{github.workspace}}/build/${ZIPNAME} ${{matrix.file}}

    - name: Compress plugin win
      if : matrix.os == 'windows-latest'
      working-directory: ${{github.workspace}}/build
      run : |
        cd Source/${env:SF_PROJECT}_artefacts/Release/VST3/${{matrix.artifact_path}}
        $ZIPNAME="${env:SF_PROJECT}-V${env:SF_VERSION}-${{matrix.artifact_name}}-vst3.zip"
        Compress-Archive -Path ${{matrix.file}} -CompressionLevel Optimal -Destination ${{github.workspace}}/build/${ZIPNAME}     

    - name: Upload plugin
      uses: actions/upload-artifact@v3
      with:
        name: ${{env.SF_PROJECT}}-V${{env.SF_VERSION}}-${{matrix.artifact_name}}-vst3.zip
        path: ${{github.workspace}}/build/${{env.SF_PROJECT}}-V${{env.SF_VERSION}}-${{matrix.artifact_name}}-vst3.zip

    - name: Build .deb
      id: build_deb
      if : matrix.os == 'ubuntu-latest'
      working-directory: ${{github.workspace}}/build
      run : bash -x ../packaging/create-deb

    - name: Upload deb
      if : matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v3
      with:
        name: ${{steps.build_deb.outputs.deb_file}}
        path: ${{github.workspace}}/build/${{steps.build_deb.outputs.deb_file}}
    
    - name : build windows installer
      if : matrix.os == 'windows-latest'
      working-directory: ${{github.workspace}}
      run: iscc /Dsrcdir="$pwd" .\packaging\windows\plugin.iss

    - name: Upload windows installer
      if : matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v3
      with:
        name: ${{env.SF_PROJECT}}-V${{env.SF_VERSION}}-${{matrix.artifact_name}}-install.exe
        path: ${{github.workspace}}/build/${{env.SF_PROJ_LOWER}}.exe


