name: User Manual to PDF

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env :
  OUTPUT_FILE : ${{vars.SF_PLUGIN_NAME}}-VX.X.X-MANUAL.pdf

jobs :
  build :
    runs-on : ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name : install markdown-pdf
        run : sudo npm install -g markdown-pdf

      - name : convert
        run : markdown-pdf -o build/${{env.OUTPUT_FILE}} docs/USER_MANUAL.md

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: ${{vars.SF_PLUGIN_NAME}}-VX.X.X-MANUAL.pdf
          path: ${{github.workspace}}/build/${{env.OUTPUT_FILE}}
