name: User Manual to PDF

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs :
  build :
    runs-on : ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name : install markdown-pdf
        run : sudo npm install -g markdown-pdf

      - name: Get Config Info
        working-directory: ${{github.workspace}}/build
        shell : bash
        run : |
          bash ../scripts/project_vars > CONFIG.sh
          cat CONFIG.sh >> "$GITHUB_ENV"
  
      - name : convert
        working-directory: ${{github.workspace}}/docs
        run : markdown-pdf -o ${{github.workspace}}/build/USER_MANUAL.pdf USER_MANUAL.md

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: ${{env.SF_PROJECT}}-${{env.SF_VERSION}}-MANUAL.pdf
          path: ${{github.workspace}}/build/USER_MANUAL.pdf
